#ifndef AT_COMMAND_LIST_H
#define AT_COMMAND_LIST_H

#ifndef SIGNAL_QUALITY_REPORT
#define SIGNAL_QUALITY_REPORT "AT+CSQ"
#endif

#ifndef COMMAND_ECHO_MODE
#define COMMAND_ECHO_MODE "ATE"
#endif

#ifndef OPERATOR_SELECTION
#define OPERATOR_SELECTION "AT+COPS"
#endif

#ifndef GET_AND_SET_MOBILE_OPERATION_BAND
#define GET_AND_SET_MOBILE_OPERATION_BAND "AT+CBAND"
#endif

#ifndef SET_DEFAULT_PSD_CONNECTION
#define SET_DEFAULT_PSD_CONNECTION "AT*MCGDEFCONT"
#endif

#ifndef CONFIG_WAKEUP_INDICATION_AT_CMD
#define CONFIG_WAKEUP_INDICATION_AT_CMD "AT+CPSMSTATUS"
#endif

#ifndef SET_BAUDRATE_AT_CMD
#define SET_BAUDRATE_AT_CMD "AT+IPR"
#endif

#ifndef CONFIG_SLOW_CLOCK_AT_CMD
#define CONFIG_SLOW_CLOCK_AT_CMD "AT+CSCLK"
#endif

#ifndef PSM_AT_CMD
#define PSM_AT_CMD "AT+CPSMS"
#endif

#ifndef NEW_MQTT
#define NEW_MQTT "AT+CMQNEW"
#endif

#ifndef SEND_MQTT_CONNECT
#define SEND_MQTT_CONNECT "AT+CMQCON"
#endif

#ifndef SEND_MQTT_PUB
#define SEND_MQTT_PUB "AT+CMQPUB"
#endif

#ifndef MQTT_DISCONNECT
#define MQTT_DISCONNECT "AT+CMQDISCON"
#endif

#endif /* AT_COMMAND_LIST_H */